apiVersion: v1
kind: PersistentVolume
metadata:
  name: notebooks-nfs
  namespace: spark-jupyter
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.0.9
    path: "/mnt/nfs"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: notebooks-nfs
  namespace: spark-jupyter
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
