apiVersion: v1
kind: PersistentVolume
metadata:
  name: notebook-nfs
  namespace: spark
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.103.231.245
    path: "/external03/isoforest"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: notebook-nfs
  namespace: spark
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
