kind: ReplicationController
apiVersion: v1
metadata:
  name: notebook-controller
  namespace: spark-jupyter
spec:
  replicas: 1
  selector:
    component: jupyter-notebook
  template:
    metadata:
      labels:
        component: jupyter-notebook
    spec:
      containers:
        - name: jupyter-notebool
          image: sahandha/jupyter
          ports:
            - containerPort: 8888 
          volumeMounts:
            - mountPath: /mnt/nfs
              name: nfsvol
          resources:
            requests:
              cpu: 100m
      volumes:
        - name: nfsvol
          persistentVolumeClaim:
            claimName: notebook-nfs

