apiVersion: v1
kind: PersistentVolume
metadata:
  name: notebook-nfs
  namespace: spark-jupyter
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.0.3
    path: "/external/spark-jupyter"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: notebook-nfs
  namespace: spark-jupyter
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
