kind: ReplicationController
apiVersion: v1
metadata:
  name: spark-worker-controller
  namespace: spark
spec:
  replicas: 4
  selector:
    component: spark-worker
  template:
    metadata:
      labels:
        component: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: sahandha/spark:kube
          imagePullPolicy: Never
          command: ["/start-worker"]
          ports:
            - containerPort: 8081
          volumeMounts:
            - mountPath: /external/spark-jupyter
              name: nfsvol
          resources:
            requests:
              cpu: 100m
      volumes:
        - name: nfsvol
          persistentVolumeClaim:
            claimName: spark-worker-nfs
