apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-master-nfs
  namespace: spark
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.103.231.245
    path: "/exports/isoforest"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: spark-master-nfs
  namespace: spark
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
