kind: ReplicationController
apiVersion: v1
metadata:
  name: spark-master-controller
  namespace: spark
spec:
  replicas: 1
  selector:
    component: spark-master
  template:
    metadata:
      labels:
        component: spark-master
    spec:
      containers:
        - name: spark-master
          image: sahandha/spark:kube     
          imagePullPolicy: Never
          command: ["/start-master"]
          ports:
            - containerPort: 7077
            - containerPort: 8080
          volumeMounts:
            - mountPath: "/external/spark-jupyter"
              name: nfsvol
          resources:
            requests:
              cpu: 100m
      volumes:
        - name: nfsvol
          persistentVolumeClaim:
            claimName: spark-master-nfs
