kind: Service
apiVersion: v1
metadata:
  name: spark-ui-proxy
  namespace: spark
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30010
  selector:
    component: spark-ui-proxy
  type: LoadBalancer
